name: Unit Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  MacOS-Test:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test with catch2
        shell: bash
        run: |
          make clean
          make test
          ./test
  Ubuntu-Test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test with catch2
        shell: bash
        run: |
          make clean
          make test
          ./test
